var cards = {
        "2": {
            "id": 2,
            "character": "Aoi",
            "cardname": "1st Anniversary",
            "unit": "Rondo",
            "type": "Elegant",
            "rarity": 4,
            "heart": 6929,
            "technical": 11919,
            "physical": 17384,
            "totalpower": 36232,
            "skill": 0.5
        },
        "3": {
            "id": 3,
            "character": "Aoi",
            "cardname": "A Guiding Hand",
            "unit": "Rondo",
            "type": "Party",
            "rarity": 4,
            "heart": 11303,
            "technical": 10815,
            "physical": 12190,
            "totalpower": 34308,
            "skill": 0.4
        },
        "4": {
            "id": 4,
            "character": "Aoi",
            "cardname": "Birthday",
            "unit": "Rondo",
            "type": "Cool",
            "rarity": 4,
            "heart": 12084,
            "technical": 11228,
            "physical": 11635,
            "totalpower": 34947,
            "skill": 0.5
        },
        "5": {
            "id": 5,
            "character": "Aoi",
            "cardname": "Black Rose Noble",
            "unit": "Rondo",
            "type": "Party",
            "rarity": 4,
            "heart": 10896,
            "technical": 11709,
            "physical": 11057,
            "totalpower": 33662,
            "skill": 0.3
        },
        "6": {
            "id": 6,
            "character": "Aoi",
            "cardname": "Demonic Ruler",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 4,
            "heart": 15989,
            "technical": 12517,
            "physical": 7098,
            "totalpower": 35604,
            "skill": 0.4
        },
        "7": {
            "id": 7,
            "character": "Aoi",
            "cardname": "Gaze of Affection",
            "unit": "Rondo",
            "type": "Party",
            "rarity": 3,
            "heart": 9531,
            "technical": 9037,
            "physical": 9223,
            "totalpower": 27791,
            "skill": 0.25
        },
        "8": {
            "id": 8,
            "character": "Aoi",
            "cardname": "Gorgeous Dance Knight",
            "unit": "Rondo",
            "type": "Cool",
            "rarity": 4,
            "heart": 12309,
            "technical": 15350,
            "physical": 6906,
            "totalpower": 34565,
            "skill": 0.4
        },
        "9": {
            "id": 9,
            "character": "Aoi",
            "cardname": "Nobleman of the Twilight",
            "unit": "Rondo",
            "type": "Street",
            "rarity": 4,
            "heart": 12050,
            "technical": 10949,
            "physical": 11252,
            "totalpower": 34251,
            "skill": 0.4
        },
        "10": {
            "id": 10,
            "character": "Aoi",
            "cardname": "Smiling Knight",
            "unit": "Rondo",
            "type": "Party",
            "rarity": 3,
            "heart": 10457,
            "technical": 7469,
            "physical": 9884,
            "totalpower": 27810,
            "skill": 0.25
        },
        "11": {
            "id": 11,
            "character": "Aoi",
            "cardname": "Songweavers of Bliss",
            "unit": "Rondo",
            "type": "Elegant",
            "rarity": 3,
            "heart": 8866,
            "technical": 10178,
            "physical": 9026,
            "totalpower": 28070,
            "skill": 0.2
        },
        "12": {
            "id": 12,
            "character": "Aoi",
            "cardname": "Waterslider Sage",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 3,
            "heart": 9528,
            "technical": 10744,
            "physical": 7036,
            "totalpower": 27308,
            "skill": 0.25
        },
        "13": {
            "id": 13,
            "character": "Dalia",
            "cardname": "1st Anniversary",
            "unit": "Mermaid",
            "type": "Cute",
            "rarity": 4,
            "heart": 12642,
            "technical": 7098,
            "physical": 17072,
            "totalpower": 36812,
            "skill": 0.5
        },
        "14": {
            "id": 14,
            "character": "Dalia",
            "cardname": "Aim Higher",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 3,
            "heart": 9180,
            "technical": 8567,
            "physical": 9557,
            "totalpower": 27304,
            "skill": 0.25
        },
        "15": {
            "id": 15,
            "character": "Dalia",
            "cardname": "Birthday",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11854,
            "technical": 10865,
            "physical": 12030,
            "totalpower": 34749,
            "skill": 0.5
        },
        "16": {
            "id": 16,
            "character": "Dalia",
            "cardname": "Dazzling Bravery",
            "unit": "Mermaid",
            "type": "Street",
            "rarity": 4,
            "heart": 10809,
            "technical": 11258,
            "physical": 11320,
            "totalpower": 33387,
            "skill": 0.4
        },
        "17": {
            "id": 17,
            "character": "Dalia",
            "cardname": "Dynamite Wave",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 3,
            "heart": 7675,
            "technical": 10332,
            "physical": 9684,
            "totalpower": 27691,
            "skill": 0.25
        },
        "18": {
            "id": 18,
            "character": "Dalia",
            "cardname": "Enchanted Shuten-doji",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 4,
            "heart": 16339,
            "technical": 6694,
            "physical": 11505,
            "totalpower": 34538,
            "skill": 0.4
        },
        "19": {
            "id": 19,
            "character": "Dalia",
            "cardname": "Lucked Out Fortune",
            "unit": "Mermaid",
            "type": "Cute",
            "rarity": 4,
            "heart": 11703,
            "technical": 11602,
            "physical": 11477,
            "totalpower": 34782,
            "skill": 0.4
        },
        "20": {
            "id": 20,
            "character": "Dalia",
            "cardname": "Passion Dancer",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 3,
            "heart": 8142,
            "technical": 9301,
            "physical": 10185,
            "totalpower": 27628,
            "skill": 0.2
        },
        "21": {
            "id": 21,
            "character": "Dalia",
            "cardname": "Presents From Out The Window",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 4,
            "heart": 12386,
            "technical": 16597,
            "physical": 7302,
            "totalpower": 36285,
            "skill": 0.5
        },
        "22": {
            "id": 22,
            "character": "Dalia",
            "cardname": "Spinning Spiral",
            "unit": "Mermaid",
            "type": "Party",
            "rarity": 4,
            "heart": 10821,
            "technical": 10524,
            "physical": 12366,
            "totalpower": 33711,
            "skill": 0.3
        },
        "23": {
            "id": 23,
            "character": "Dalia",
            "cardname": "Whirling Flower Red Carpet Blossoms",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 4,
            "heart": 6698,
            "technical": 12428,
            "physical": 16863,
            "totalpower": 35989,
            "skill": 0.5
        },
        "24": {
            "id": 24,
            "character": "Dalia",
            "cardname": "With You",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 3,
            "heart": 9683,
            "technical": 7577,
            "physical": 10481,
            "totalpower": 27741,
            "skill": 0.25
        },
        "25": {
            "id": 25,
            "character": "Esora",
            "cardname": "1st Anniversary",
            "unit": "Peaky",
            "type": "Cute",
            "rarity": 4,
            "heart": 6588,
            "technical": 15987,
            "physical": 13436,
            "totalpower": 36011,
            "skill": 0.5
        },
        "26": {
            "id": 26,
            "character": "Esora",
            "cardname": "All Aboard Trance",
            "unit": "Peaky",
            "type": "Cute",
            "rarity": 4,
            "heart": 11825,
            "technical": 10519,
            "physical": 11121,
            "totalpower": 33465,
            "skill": 0.3
        },
        "27": {
            "id": 27,
            "character": "Esora",
            "cardname": "Birthday",
            "unit": "Peaky",
            "type": "Cool",
            "rarity": 4,
            "heart": 11969,
            "technical": 11033,
            "physical": 11501,
            "totalpower": 34503,
            "skill": 0.5
        },
        "28": {
            "id": 28,
            "character": "Esora",
            "cardname": "Dew Brilliant",
            "unit": "Peaky",
            "type": "Street",
            "rarity": 4,
            "heart": 15906,
            "technical": 11927,
            "physical": 6809,
            "totalpower": 34642,
            "skill": 0.4
        },
        "29": {
            "id": 29,
            "character": "Esora",
            "cardname": "Ephemeral Foxy Lady",
            "unit": "Peaky",
            "type": "Cool",
            "rarity": 3,
            "heart": 9266,
            "technical": 8802,
            "physical": 9259,
            "totalpower": 27327,
            "skill": 0.25
        },
        "30": {
            "id": 30,
            "character": "Esora",
            "cardname": "Happy New Year 2022",
            "unit": "Peaky",
            "type": "Elegant",
            "rarity": 4,
            "heart": 16929,
            "technical": 6979,
            "physical": 12473,
            "totalpower": 36381,
            "skill": 0.5
        },
        "31": {
            "id": 31,
            "character": "Esora",
            "cardname": "Starlit Sweet Poison",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 4,
            "heart": 12148,
            "technical": 11083,
            "physical": 12038,
            "totalpower": 35269,
            "skill": 0.4
        },
        "32": {
            "id": 32,
            "character": "Esora",
            "cardname": "Sunshine Lovely",
            "unit": "Peaky",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11941,
            "technical": 16126,
            "physical": 6618,
            "totalpower": 34685,
            "skill": "40+15%"
        },
        "33": {
            "id": 33,
            "character": "Esora",
            "cardname": "Vainglory 3 out",
            "unit": "Peaky",
            "type": "Street",
            "rarity": 3,
            "heart": 9860,
            "technical": 8692,
            "physical": 8588,
            "totalpower": 27140,
            "skill": 0.2
        },
        "34": {
            "id": 34,
            "character": "Esora",
            "cardname": "Veteran",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 4,
            "heart": 11487,
            "technical": 6847,
            "physical": 16989,
            "totalpower": 35323,
            "skill": 0.4
        },
        "35": {
            "id": 35,
            "character": "Haruna",
            "cardname": "1st Anniversary",
            "unit": "LyriLily",
            "type": "Cute",
            "rarity": 4,
            "heart": 7048,
            "technical": 13025,
            "physical": 15762,
            "totalpower": 35835,
            "skill": 0.5
        },
        "36": {
            "id": 36,
            "character": "Haruna",
            "cardname": "A Clean And Fresh Stage",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 3,
            "heart": 8860,
            "technical": 9593,
            "physical": 9616,
            "totalpower": 28069,
            "skill": 0.25
        },
        "37": {
            "id": 37,
            "character": "Haruna",
            "cardname": "Birthday",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 4,
            "heart": 11518,
            "technical": 11899,
            "physical": 11313,
            "totalpower": 34730,
            "skill": 0.5
        },
        "38": {
            "id": 38,
            "character": "Haruna",
            "cardname": "Caramel on Top",
            "unit": "LyriLily",
            "type": "Elegant",
            "rarity": 3,
            "heart": 9412,
            "technical": 10092,
            "physical": 8473,
            "totalpower": 27977,
            "skill": 0.25
        },
        "39": {
            "id": 39,
            "character": "Haruna",
            "cardname": "Cinderella at the Stroke of Midnight",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 3,
            "heart": 8827,
            "technical": 9982,
            "physical": 9657,
            "totalpower": 28466,
            "skill": 0.25
        },
        "40": {
            "id": 40,
            "character": "Haruna",
            "cardname": "DJ for Life",
            "unit": "LyriLily",
            "type": "Cute",
            "rarity": 3,
            "heart": 9985,
            "technical": 9087,
            "physical": 9656,
            "totalpower": 28728,
            "skill": 0.2
        },
        "41": {
            "id": 41,
            "character": "Haruna",
            "cardname": "Hearts of Love, Hues of Aqua",
            "unit": "LyriLily",
            "type": "Street",
            "rarity": 4,
            "heart": 11290,
            "technical": 10804,
            "physical": 12183,
            "totalpower": 34277,
            "skill": 0.4
        },
        "42": {
            "id": 42,
            "character": "Haruna",
            "cardname": "Lyrical Lily DJ",
            "unit": "LyriLily",
            "type": "Party",
            "rarity": 4,
            "heart": 16058,
            "technical": 11384,
            "physical": 6707,
            "totalpower": 34149,
            "skill": 0.6
        },
        "43": {
            "id": 43,
            "character": "Haruna",
            "cardname": "Run Like Hell",
            "unit": "LyriLily",
            "type": "Cute",
            "rarity": 4,
            "heart": 11296,
            "technical": 11714,
            "physical": 11487,
            "totalpower": 34497,
            "skill": 0.4
        },
        "44": {
            "id": 44,
            "character": "Haruna",
            "cardname": "Seiryuu Sword Slash",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 4,
            "heart": 17287,
            "technical": 6721,
            "physical": 12484,
            "totalpower": 36492,
            "skill": 0.5
        },
        "45": {
            "id": 45,
            "character": "Haruna",
            "cardname": "The Witness Carnation",
            "unit": "LyriLily",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11885,
            "technical": 11505,
            "physical": 11610,
            "totalpower": 35000,
            "skill": 0.6
        },
        "46": {
            "id": 46,
            "character": "Haruna",
            "cardname": "Turquoise Rococo",
            "unit": "LyriLily",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11674,
            "technical": 11591,
            "physical": 10312,
            "totalpower": 33577,
            "skill": 0.3
        },
        "47": {
            "id": 47,
            "character": "Hiiro",
            "cardname": "1st Anniversary",
            "unit": "Rondo",
            "type": "Party",
            "rarity": 4,
            "heart": 12179,
            "technical": 6710,
            "physical": 17810,
            "totalpower": 36699,
            "skill": 0.5
        },
        "48": {
            "id": 48,
            "character": "Hiiro",
            "cardname": "Birthday",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 4,
            "heart": 11962,
            "technical": 11345,
            "physical": 10678,
            "totalpower": 33985,
            "skill": 0.5
        },
        "49": {
            "id": 49,
            "character": "Hiiro",
            "cardname": "Birthday",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 4,
            "heart": 11962,
            "technical": 11345,
            "physical": 10678,
            "totalpower": 33985,
            "skill": 0.5
        },
        "50": {
            "id": 50,
            "character": "Hiiro",
            "cardname": "Carpet of Sunflowers",
            "unit": "Rondo",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11155,
            "technical": 12115,
            "physical": 11730,
            "totalpower": 35000,
            "skill": 0.6
        },
        "51": {
            "id": 51,
            "character": "Hiiro",
            "cardname": "Dancer of the Full Moon",
            "unit": "Rondo",
            "type": "Street",
            "rarity": 3,
            "heart": 8825,
            "technical": 9363,
            "physical": 9441,
            "totalpower": 27629,
            "skill": 0.25
        },
        "52": {
            "id": 52,
            "character": "Hiiro",
            "cardname": "Enchanting Voice",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 3,
            "heart": 10181,
            "technical": 10036,
            "physical": 8163,
            "totalpower": 28380,
            "skill": 0.25
        },
        "53": {
            "id": 53,
            "character": "Hiiro",
            "cardname": "Gorgeous Dance Princess",
            "unit": "Rondo",
            "type": "Cool",
            "rarity": 4,
            "heart": 6236,
            "technical": 15363,
            "physical": 12257,
            "totalpower": 33856,
            "skill": 0.4
        },
        "54": {
            "id": 54,
            "character": "Hiiro",
            "cardname": "Pale Red Magical DJ",
            "unit": "Rondo",
            "type": "Elegant",
            "rarity": 4,
            "heart": 15144,
            "technical": 12753,
            "physical": 6880,
            "totalpower": 34777,
            "skill": 0.4
        },
        "55": {
            "id": 55,
            "character": "Hiiro",
            "cardname": "Purple Rose Dancer",
            "unit": "Rondo",
            "type": "Street",
            "rarity": 4,
            "heart": 12595,
            "technical": 10772,
            "physical": 10863,
            "totalpower": 34230,
            "skill": 0.3
        },
        "56": {
            "id": 56,
            "character": "Hiiro",
            "cardname": "Smile In Pink",
            "unit": "Rondo",
            "type": "Party",
            "rarity": 4,
            "heart": 11256,
            "technical": 11672,
            "physical": 10342,
            "totalpower": 33270,
            "skill": 0.4
        },
        "57": {
            "id": 57,
            "character": "Hiiro",
            "cardname": "Spellbinding Dance",
            "unit": "Rondo",
            "type": "Cool",
            "rarity": 3,
            "heart": 10410,
            "technical": 9325,
            "physical": 8617,
            "totalpower": 28352,
            "skill": 0.2
        },
        "58": {
            "id": 58,
            "character": "Hiiro",
            "cardname": "The Agent of Enchantment",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 3,
            "heart": 10399,
            "technical": 7789,
            "physical": 9738,
            "totalpower": 27926,
            "skill": 0.25
        },
        "59": {
            "id": 59,
            "character": "Ibuki",
            "cardname": "1st Anniversary",
            "unit": "Photon",
            "type": "Party",
            "rarity": 4,
            "heart": 13264,
            "technical": 15189,
            "physical": 7207,
            "totalpower": 35660,
            "skill": 0.5
        },
        "60": {
            "id": 60,
            "character": "Ibuki",
            "cardname": "Birthday",
            "unit": "Photon",
            "type": "Cute",
            "rarity": 4,
            "heart": 11217,
            "technical": 11010,
            "physical": 12552,
            "totalpower": 34779,
            "skill": 0.5
        },
        "61": {
            "id": 61,
            "character": "Ibuki",
            "cardname": "Cutting Edge",
            "unit": "Photon",
            "type": "Cute",
            "rarity": 3,
            "heart": 8878,
            "technical": 8102,
            "physical": 10531,
            "totalpower": 27511,
            "skill": 0.2
        },
        "62": {
            "id": 62,
            "character": "Ibuki",
            "cardname": "Dancing Splash",
            "unit": "Photon",
            "type": "Cute",
            "rarity": 4,
            "heart": 15613,
            "technical": 7088,
            "physical": 11730,
            "totalpower": 34431,
            "skill": "40+15%"
        },
        "63": {
            "id": 63,
            "character": "Ibuki",
            "cardname": "Dokidoki Heartbeat",
            "unit": "Photon",
            "type": "Street",
            "rarity": 4,
            "heart": 7207,
            "technical": 16380,
            "physical": 12772,
            "totalpower": 36359,
            "skill": 0.5
        },
        "64": {
            "id": 64,
            "character": "Ibuki",
            "cardname": "Earth-Riding Maiden Girl",
            "unit": "Photon",
            "type": "Cool",
            "rarity": 3,
            "heart": 10349,
            "technical": 7390,
            "physical": 9770,
            "totalpower": 27509,
            "skill": 0.25
        },
        "65": {
            "id": 65,
            "character": "Ibuki",
            "cardname": "Female Leopard",
            "unit": "Photon",
            "type": "Street",
            "rarity": 3,
            "heart": 9231,
            "technical": 8541,
            "physical": 10575,
            "totalpower": 28347,
            "skill": 0.25
        },
        "66": {
            "id": 66,
            "character": "Ibuki",
            "cardname": "Gleaming Clematis",
            "unit": "Photon",
            "type": "Street",
            "rarity": 4,
            "heart": 6875,
            "technical": 12456,
            "physical": 16043,
            "totalpower": 35374,
            "skill": 0.4
        },
        "67": {
            "id": 67,
            "character": "Ibuki",
            "cardname": "Illuminator",
            "unit": "Photon",
            "type": "Cool",
            "rarity": 4,
            "heart": 11155,
            "technical": 11046,
            "physical": 12343,
            "totalpower": 34544,
            "skill": 0.3
        },
        "68": {
            "id": 68,
            "character": "Ibuki",
            "cardname": "Magic Macaroon",
            "unit": "Photon",
            "type": "Cute",
            "rarity": 3,
            "heart": 9395,
            "technical": 9769,
            "physical": 8595,
            "totalpower": 27759,
            "skill": 0.25
        },
        "69": {
            "id": 69,
            "character": "Kurumi",
            "cardname": "1st Anniversary",
            "unit": "LyriLily",
            "type": "Elegant",
            "rarity": 4,
            "heart": 17473,
            "technical": 7259,
            "physical": 11714,
            "totalpower": 36446,
            "skill": 0.5
        },
        "70": {
            "id": 70,
            "character": "Kurumi",
            "cardname": "Birthday Garden",
            "unit": "LyriLily",
            "type": "Street",
            "rarity": 4,
            "heart": 12309,
            "technical": 12415,
            "physical": 12072,
            "totalpower": 36796,
            "skill": 0.55
        },
        "71": {
            "id": 71,
            "character": "Kurumi",
            "cardname": "Birthday",
            "unit": "LyriLily",
            "type": "Party",
            "rarity": 4,
            "heart": 10444,
            "technical": 12387,
            "physical": 11213,
            "totalpower": 34044,
            "skill": 0.5
        },
        "72": {
            "id": 72,
            "character": "Kurumi",
            "cardname": "Garden Fairy",
            "unit": "LyriLily",
            "type": "Cute",
            "rarity": 4,
            "heart": 10924,
            "technical": 9956,
            "physical": 12567,
            "totalpower": 33447,
            "skill": 0.3
        },
        "73": {
            "id": 73,
            "character": "Kurumi",
            "cardname": "Interceptor Attack! Snow Drop Kunai",
            "unit": "LyriLily",
            "type": "Party",
            "rarity": 3,
            "heart": 8490,
            "technical": 10767,
            "physical": 12538,
            "totalpower": 31795,
            "skill": 0.25
        },
        "74": {
            "id": 74,
            "character": "Kurumi",
            "cardname": "Journey In The Sky",
            "unit": "LyriLily",
            "type": "Cute",
            "rarity": 3,
            "heart": 11897,
            "technical": 9248,
            "physical": 11034,
            "totalpower": 32179,
            "skill": 0.25
        },
        "75": {
            "id": 75,
            "character": "Kurumi",
            "cardname": "Little Red Riding Hood in the Forest",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 4,
            "heart": 11447,
            "technical": 11198,
            "physical": 10933,
            "totalpower": 33578,
            "skill": "40+15%"
        },
        "76": {
            "id": 76,
            "character": "Kurumi",
            "cardname": "Mischievous Fairy",
            "unit": "LyriLily",
            "type": "Cute",
            "rarity": 3,
            "heart": 9013,
            "technical": 8827,
            "physical": 9582,
            "totalpower": 27422,
            "skill": 0.25
        },
        "77": {
            "id": 77,
            "character": "Kurumi",
            "cardname": "Naughty Tonfa Girl",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 3,
            "heart": 11848,
            "technical": 11649,
            "physical": 8416,
            "totalpower": 31913,
            "skill": 0.25
        },
        "78": {
            "id": 78,
            "character": "Kurumi",
            "cardname": "Pekora-oudspeaker",
            "unit": "LyriLily",
            "type": "Street",
            "rarity": 4,
            "heart": 10823,
            "technical": 11041,
            "physical": 11860,
            "totalpower": 33724,
            "skill": 0.4
        },
        "79": {
            "id": 79,
            "character": "Kurumi",
            "cardname": "Surprise Smile",
            "unit": "LyriLily",
            "type": "Elegant",
            "rarity": 4,
            "heart": 6804,
            "technical": 15987,
            "physical": 11984,
            "totalpower": 34775,
            "skill": "40+15%"
        },
        "80": {
            "id": 80,
            "character": "Kurumi",
            "cardname": "Swaying In The Wind",
            "unit": "LyriLily",
            "type": "Street",
            "rarity": 3,
            "heart": 8540,
            "technical": 8681,
            "physical": 9976,
            "totalpower": 27197,
            "skill": 0.2
        },
        "81": {
            "id": 81,
            "character": "Kyoko",
            "cardname": "1st Anniversary",
            "unit": "Peaky",
            "type": "Elegant",
            "rarity": 4,
            "heart": 16631,
            "technical": 12336,
            "physical": 7239,
            "totalpower": 36206,
            "skill": 0.5
        },
        "82": {
            "id": 82,
            "character": "Kyoko",
            "cardname": "Azure Sky -AMAZING-",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 4,
            "heart": 7288,
            "technical": 12078,
            "physical": 15306,
            "totalpower": 34672,
            "skill": 0.4
        },
        "83": {
            "id": 83,
            "character": "Kyoko",
            "cardname": "Birthday",
            "unit": "Peaky",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11980,
            "technical": 11717,
            "physical": 11487,
            "totalpower": 35184,
            "skill": 0.5
        },
        "84": {
            "id": 84,
            "character": "Kyoko",
            "cardname": "Destination Heaven",
            "unit": "Peaky",
            "type": "Cool",
            "rarity": 4,
            "heart": 11799,
            "technical": 11693,
            "physical": 11552,
            "totalpower": 35044,
            "skill": 0.3
        },
        "85": {
            "id": 85,
            "character": "Kyoko",
            "cardname": "Encouragement",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 3,
            "heart": 9557,
            "technical": 7915,
            "physical": 9840,
            "totalpower": 27312,
            "skill": 0.25
        },
        "86": {
            "id": 86,
            "character": "Kyoko",
            "cardname": "Irresistable Force 2022",
            "unit": "Peaky",
            "type": "Elegant",
            "rarity": 3,
            "heart": 12570,
            "technical": 8959,
            "physical": 10614,
            "totalpower": 32143,
            "skill": 0.25
        },
        "87": {
            "id": 87,
            "character": "Kyoko",
            "cardname": "Moonlight Behold",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 3,
            "heart": 9629,
            "technical": 9132,
            "physical": 8635,
            "totalpower": 27396,
            "skill": 0.25
        },
        "88": {
            "id": 88,
            "character": "Kyoko",
            "cardname": "Peaky Popping",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 4,
            "heart": 6860,
            "technical": 15367,
            "physical": 12320,
            "totalpower": 34547,
            "skill": "40+15%"
        },
        "89": {
            "id": 89,
            "character": "Kyoko",
            "cardname": "Red Rain Breathtaking",
            "unit": "Peaky",
            "type": "Street",
            "rarity": 3,
            "heart": 9984,
            "technical": 8247,
            "physical": 9050,
            "totalpower": 27281,
            "skill": 0.25
        },
        "90": {
            "id": 90,
            "character": "Kyoko",
            "cardname": "Soaring Heart Beat",
            "unit": "Peaky",
            "type": "Street",
            "rarity": 4,
            "heart": 11302,
            "technical": 10606,
            "physical": 11463,
            "totalpower": 33371,
            "skill": 0.4
        },
        "91": {
            "id": 91,
            "character": "Kyoko",
            "cardname": "Universe Lock On",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 3,
            "heart": 9486,
            "technical": 9327,
            "physical": 9383,
            "totalpower": 28196,
            "skill": 0.2
        },
        "92": {
            "id": 92,
            "character": "Maho",
            "cardname": "1st Anniversary",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 4,
            "heart": 13334,
            "technical": 7433,
            "physical": 16066,
            "totalpower": 36833,
            "skill": 0.5
        },
        "93": {
            "id": 93,
            "character": "Maho",
            "cardname": "Birthday",
            "unit": "HapiAra",
            "type": "Cool",
            "rarity": 4,
            "heart": 11917,
            "technical": 11260,
            "physical": 11645,
            "totalpower": 34822,
            "skill": 0.5
        },
        "94": {
            "id": 94,
            "character": "Maho",
            "cardname": "Delight Remix",
            "unit": "HapiAra",
            "type": "Elegant",
            "rarity": 4,
            "heart": 10432,
            "technical": 11897,
            "physical": 11274,
            "totalpower": 33603,
            "skill": 0.3
        },
        "95": {
            "id": 95,
            "character": "Maho",
            "cardname": "Electric Parade",
            "unit": "HapiAra",
            "type": "Cool",
            "rarity": 3,
            "heart": 8876,
            "technical": 9874,
            "physical": 8973,
            "totalpower": 27723,
            "skill": 0.2
        },
        "96": {
            "id": 96,
            "character": "Maho",
            "cardname": "Esoteric Art! Silver Flow and Flash",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 3,
            "heart": 10868,
            "technical": 9101,
            "physical": 11938,
            "totalpower": 31907,
            "skill": 0.25
        },
        "97": {
            "id": 97,
            "character": "Maho",
            "cardname": "Floating Rainbow",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 3,
            "heart": 7824,
            "technical": 10274,
            "physical": 9879,
            "totalpower": 27977,
            "skill": 0.25
        },
        "98": {
            "id": 98,
            "character": "Maho",
            "cardname": "New Year Good Fortune 2021",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 4,
            "heart": 10953,
            "technical": 10888,
            "physical": 11721,
            "totalpower": 33562,
            "skill": 0.4
        },
        "99": {
            "id": 99,
            "character": "Maho",
            "cardname": "This Fist is for My Friends",
            "unit": "HapiAra",
            "type": "Cute",
            "rarity": 4,
            "heart": 11061,
            "technical": 11627,
            "physical": 11932,
            "totalpower": 34620,
            "skill": 0.4
        },
        "100": {
            "id": 100,
            "character": "Maho",
            "cardname": "Tropical Icecandy",
            "unit": "HapiAra",
            "type": "Street",
            "rarity": 4,
            "heart": 6941,
            "technical": 16592,
            "physical": 10824,
            "totalpower": 34357,
            "skill": "40+15%"
        },
        "101": {
            "id": 101,
            "character": "Maho",
            "cardname": "Which Do You Want",
            "unit": "HapiAra",
            "type": "Elegant",
            "rarity": 3,
            "heart": 9887,
            "technical": 8337,
            "physical": 13110,
            "totalpower": 31334,
            "skill": 0.25
        },
        "102": {
            "id": 102,
            "character": "Maho",
            "cardname": "Wholehearted Dedication",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 3,
            "heart": 7831,
            "technical": 9679,
            "physical": 9970,
            "totalpower": 27480,
            "skill": 0.25
        },
        "103": {
            "id": 103,
            "character": "Marika",
            "cardname": "1st Anniversary",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 4,
            "heart": 6940,
            "technical": 12816,
            "physical": 15906,
            "totalpower": 35662,
            "skill": 0.5
        },
        "104": {
            "id": 104,
            "character": "Marika",
            "cardname": "Birthday",
            "unit": "Mermaid",
            "type": "Party",
            "rarity": 4,
            "heart": 12138,
            "technical": 11469,
            "physical": 11075,
            "totalpower": 34682,
            "skill": 0.5
        },
        "105": {
            "id": 105,
            "character": "Marika",
            "cardname": "Creamy Snowflake",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 3,
            "heart": 9986,
            "technical": 9167,
            "physical": 9243,
            "totalpower": 28396,
            "skill": 0.25
        },
        "106": {
            "id": 106,
            "character": "Marika",
            "cardname": "Glittering Shower",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 4,
            "heart": 10895,
            "technical": 11253,
            "physical": 11988,
            "totalpower": 34136,
            "skill": 0.4
        },
        "107": {
            "id": 107,
            "character": "Marika",
            "cardname": "Heavenly Stairway",
            "unit": "Mermaid",
            "type": "Street",
            "rarity": 4,
            "heart": 11272,
            "technical": 11185,
            "physical": 11033,
            "totalpower": 33490,
            "skill": 0.4
        },
        "108": {
            "id": 108,
            "character": "Marika",
            "cardname": "Huge Thrill",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 3,
            "heart": 9896,
            "technical": 8355,
            "physical": 8905,
            "totalpower": 27156,
            "skill": 0.2
        },
        "109": {
            "id": 109,
            "character": "Marika",
            "cardname": "Night Descends",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11340,
            "technical": 11477,
            "physical": 11255,
            "totalpower": 34072,
            "skill": 0.3
        },
        "110": {
            "id": 110,
            "character": "Marika",
            "cardname": "Rolling Destiny",
            "unit": "Mermaid",
            "type": "Cute",
            "rarity": 3,
            "heart": 9444,
            "technical": 9255,
            "physical": 9580,
            "totalpower": 28279,
            "skill": 0.25
        },
        "111": {
            "id": 111,
            "character": "Marika",
            "cardname": "Snowy Holy Night Street Corner",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 3,
            "heart": 10926,
            "technical": 12504,
            "physical": 8751,
            "totalpower": 32181,
            "skill": 0.25
        },
        "112": {
            "id": 112,
            "character": "Marika",
            "cardname": "The Joy Of Vowing Love",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 3,
            "heart": 8068,
            "technical": 9414,
            "physical": 10303,
            "totalpower": 27785,
            "skill": 0.25
        },
        "113": {
            "id": 113,
            "character": "Marika",
            "cardname": "Whirling Flower Red Carpet Vibrant",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 4,
            "heart": 12260,
            "technical": 6850,
            "physical": 16385,
            "totalpower": 35495,
            "skill": 0.5
        },
        "114": {
            "id": 114,
            "character": "Michiru",
            "cardname": "Supernova",
            "unit": "Common",
            "type": "Cute",
            "rarity": 4,
            "heart": 12461,
            "technical": 12369,
            "physical": 13037,
            "totalpower": 37867,
            "skill": 0.4
        },
        "115": {
            "id": 115,
            "character": "Miiko",
            "cardname": "1st Anniversary",
            "unit": "LyriLily",
            "type": "Street",
            "rarity": 4,
            "heart": 6888,
            "technical": 16219,
            "physical": 12915,
            "totalpower": 36022,
            "skill": 0.5
        },
        "116": {
            "id": 116,
            "character": "Miiko",
            "cardname": "Bashful Wink",
            "unit": "LyriLily",
            "type": "Party",
            "rarity": 3,
            "heart": 9860,
            "technical": 9406,
            "physical": 9274,
            "totalpower": 28540,
            "skill": 0.25
        },
        "117": {
            "id": 117,
            "character": "Miiko",
            "cardname": "Birthday",
            "unit": "LyriLily",
            "type": "Elegant",
            "rarity": 4,
            "heart": 10849,
            "technical": 11673,
            "physical": 11174,
            "totalpower": 33696,
            "skill": 0.5
        },
        "118": {
            "id": 118,
            "character": "Miiko",
            "cardname": "Captive Sleeping Beauty",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 4,
            "heart": 11759,
            "technical": 10952,
            "physical": 10761,
            "totalpower": 33472,
            "skill": "40+15%"
        },
        "119": {
            "id": 119,
            "character": "Miiko",
            "cardname": "Fluttering Skirts",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 3,
            "heart": 10338,
            "technical": 9054,
            "physical": 8671,
            "totalpower": 28063,
            "skill": 0.2
        },
        "120": {
            "id": 120,
            "character": "Miiko",
            "cardname": "Jade Magical DJ",
            "unit": "LyriLily",
            "type": "Elegant",
            "rarity": 3,
            "heart": 10247,
            "technical": 9609,
            "physical": 7557,
            "totalpower": 27413,
            "skill": 0.25
        },
        "121": {
            "id": 121,
            "character": "Miiko",
            "cardname": "Our Little Secret",
            "unit": "LyriLily",
            "type": "Cute",
            "rarity": 4,
            "heart": 11916,
            "technical": 10971,
            "physical": 11456,
            "totalpower": 34343,
            "skill": 0.4
        },
        "122": {
            "id": 122,
            "character": "Miiko",
            "cardname": "Shimmering Fubuki Confetti",
            "unit": "LyriLily",
            "type": "Street",
            "rarity": 3,
            "heart": 8939,
            "technical": 9017,
            "physical": 9333,
            "totalpower": 27289,
            "skill": 0.25
        },
        "123": {
            "id": 123,
            "character": "Miiko",
            "cardname": "Special Move! Heavy Snow Gatling Gun",
            "unit": "LyriLily",
            "type": "Party",
            "rarity": 4,
            "heart": 12475,
            "technical": 6885,
            "physical": 17030,
            "totalpower": 36390,
            "skill": 0.5
        },
        "124": {
            "id": 124,
            "character": "Miiko",
            "cardname": "White Rose Innocence",
            "unit": "LyriLily",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11738,
            "technical": 6611,
            "physical": 15697,
            "totalpower": 34046,
            "skill": 0.4
        },
        "125": {
            "id": 125,
            "character": "Miiko",
            "cardname": "Wisteria Butterfly",
            "unit": "LyriLily",
            "type": "Party",
            "rarity": 4,
            "heart": 12401,
            "technical": 11255,
            "physical": 11098,
            "totalpower": 34754,
            "skill": 0.3
        },
        "126": {
            "id": 126,
            "character": "Miiko",
            "cardname": "With Mr. Jiangshi",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 4,
            "heart": 16309,
            "technical": 12455,
            "physical": 7015,
            "totalpower": 35779,
            "skill": 0.5
        },
        "127": {
            "id": 127,
            "character": "Miyu",
            "cardname": "1st Anniversary",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 4,
            "heart": 16189,
            "technical": 12939,
            "physical": 6908,
            "totalpower": 36036,
            "skill": 0.5
        },
        "128": {
            "id": 128,
            "character": "Miyu",
            "cardname": "Birthday Garden",
            "unit": "LyriLily",
            "type": "Party",
            "rarity": 4,
            "heart": 12723,
            "technical": 12538,
            "physical": 11407,
            "totalpower": 36668,
            "skill": 0.55
        },
        "129": {
            "id": 129,
            "character": "Miyu",
            "cardname": "Birthday",
            "unit": "LyriLily",
            "type": "Street",
            "rarity": 4,
            "heart": 11258,
            "technical": 12062,
            "physical": 11275,
            "totalpower": 34595,
            "skill": 0.5
        },
        "130": {
            "id": 130,
            "character": "Miyu",
            "cardname": "Deliver It To Everyone",
            "unit": "LyriLily",
            "type": "Party",
            "rarity": 3,
            "heart": 10363,
            "technical": 9893,
            "physical": 7656,
            "totalpower": 27912,
            "skill": 0.25
        },
        "131": {
            "id": 131,
            "character": "Miyu",
            "cardname": "Fine Tea Party",
            "unit": "LyriLily",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11207,
            "technical": 12316,
            "physical": 10798,
            "totalpower": 34321,
            "skill": 0.4
        },
        "132": {
            "id": 132,
            "character": "Miyu",
            "cardname": "Happiness Petals",
            "unit": "LyriLily",
            "type": "Cute",
            "rarity": 4,
            "heart": 11736,
            "technical": 16378,
            "physical": 6732,
            "totalpower": 34846,
            "skill": 0.4
        },
        "133": {
            "id": 133,
            "character": "Miyu",
            "cardname": "Hummingbird Flight",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 4,
            "heart": 12661,
            "technical": 10612,
            "physical": 10979,
            "totalpower": 34252,
            "skill": 0.3
        },
        "134": {
            "id": 134,
            "character": "Miyu",
            "cardname": "Shiny Wing",
            "unit": "LyriLily",
            "type": "Party",
            "rarity": 4,
            "heart": 11065,
            "technical": 11123,
            "physical": 11156,
            "totalpower": 33344,
            "skill": "40+15%"
        },
        "135": {
            "id": 135,
            "character": "Miyu",
            "cardname": "Sleds Soaring High",
            "unit": "LyriLily",
            "type": "Cute",
            "rarity": 3,
            "heart": 9652,
            "technical": 9281,
            "physical": 9360,
            "totalpower": 28293,
            "skill": 0.25
        },
        "136": {
            "id": 136,
            "character": "Miyu",
            "cardname": "Smooth Shine",
            "unit": "LyriLily",
            "type": "Party",
            "rarity": 3,
            "heart": 10692,
            "technical": 8384,
            "physical": 9196,
            "totalpower": 28272,
            "skill": 0.2
        },
        "137": {
            "id": 137,
            "character": "Miyu",
            "cardname": "Snow White In The Mirror",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 3,
            "heart": 9082,
            "technical": 8640,
            "physical": 9848,
            "totalpower": 27570,
            "skill": 0.25
        },
        "138": {
            "id": 138,
            "character": "Miyu",
            "cardname": "Starlit Hoshimachi Duet",
            "unit": "LyriLily",
            "type": "Street",
            "rarity": 3,
            "heart": 9347,
            "technical": 9095,
            "physical": 9418,
            "totalpower": 27860,
            "skill": 0.25
        },
        "139": {
            "id": 139,
            "character": "Miyu",
            "cardname": "Tai Chi With Panda",
            "unit": "LyriLily",
            "type": "Cool",
            "rarity": 3,
            "heart": 12292,
            "technical": 9068,
            "physical": 9954,
            "totalpower": 31314,
            "skill": 0.25
        },
        "140": {
            "id": 140,
            "character": "Miyu",
            "cardname": "White Rose Purity",
            "unit": "LyriLily",
            "type": "Elegant",
            "rarity": 4,
            "heart": 6437,
            "technical": 11260,
            "physical": 16544,
            "totalpower": 34241,
            "skill": 0.4
        },
        "141": {
            "id": 141,
            "character": "Muni",
            "cardname": "1st Anniversary",
            "unit": "HapiAra",
            "type": "Cool",
            "rarity": 4,
            "heart": 6859,
            "technical": 17041,
            "physical": 12346,
            "totalpower": 36246,
            "skill": 0.5
        },
        "142": {
            "id": 142,
            "character": "Muni",
            "cardname": "Amanojaku Cappucino",
            "unit": "HapiAra",
            "type": "Street",
            "rarity": 4,
            "heart": 14213,
            "technical": 7076,
            "physical": 13835,
            "totalpower": 35124,
            "skill": 0.6
        },
        "143": {
            "id": 143,
            "character": "Muni",
            "cardname": "Around Go-round",
            "unit": "HapiAra",
            "type": "Elegant",
            "rarity": 3,
            "heart": 8532,
            "technical": 10405,
            "physical": 8617,
            "totalpower": 27554,
            "skill": 0.2
        },
        "144": {
            "id": 144,
            "character": "Muni",
            "cardname": "Attract With Sweet Scent",
            "unit": "HapiAra",
            "type": "Elegant",
            "rarity": 4,
            "heart": 6512,
            "technical": 12863,
            "physical": 16823,
            "totalpower": 36198,
            "skill": 0.5
        },
        "145": {
            "id": 145,
            "character": "Muni",
            "cardname": "Birthday",
            "unit": "HapiAra",
            "type": "Cute",
            "rarity": 4,
            "heart": 12221,
            "technical": 10977,
            "physical": 11058,
            "totalpower": 34256,
            "skill": 0.5
        },
        "146": {
            "id": 146,
            "character": "Muni",
            "cardname": "Candy Paradise",
            "unit": "HapiAra",
            "type": "Elegant",
            "rarity": 3,
            "heart": 9222,
            "technical": 10162,
            "physical": 8978,
            "totalpower": 28362,
            "skill": 0.25
        },
        "147": {
            "id": 147,
            "character": "Muni",
            "cardname": "Cuties Only",
            "unit": "HapiAra",
            "type": "Cool",
            "rarity": 4,
            "heart": 10775,
            "technical": 12746,
            "physical": 11253,
            "totalpower": 34774,
            "skill": 0.3
        },
        "148": {
            "id": 148,
            "character": "Muni",
            "cardname": "Daybreak Jewel",
            "unit": "HapiAra",
            "type": "Cute",
            "rarity": 4,
            "heart": 16528,
            "technical": 12828,
            "physical": 6881,
            "totalpower": 36237,
            "skill": 0.5
        },
        "149": {
            "id": 149,
            "character": "Muni",
            "cardname": "Fortune Favors Smiles 2021",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 4,
            "heart": 11419,
            "technical": 11216,
            "physical": 11391,
            "totalpower": 34026,
            "skill": 0.4
        },
        "150": {
            "id": 150,
            "character": "Muni",
            "cardname": "Sailing Dolphin",
            "unit": "HapiAra",
            "type": "Street",
            "rarity": 3,
            "heart": 9737,
            "technical": 10190,
            "physical": 7501,
            "totalpower": 27428,
            "skill": 0.25
        },
        "151": {
            "id": 151,
            "character": "Muni",
            "cardname": "Sparkling Bunny",
            "unit": "HapiAra",
            "type": "Cute",
            "rarity": 3,
            "heart": 10332,
            "technical": 7662,
            "physical": 9334,
            "totalpower": 27328,
            "skill": 0.25
        },
        "152": {
            "id": 152,
            "character": "Muni",
            "cardname": "The One and Only Tulip",
            "unit": "HapiAra",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11710,
            "technical": 12200,
            "physical": 11090,
            "totalpower": 35000,
            "skill": 0.6
        },
        "153": {
            "id": 153,
            "character": "Muni",
            "cardname": "Volley! Giant Nyochio Cannon",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 4,
            "heart": 7339,
            "technical": 12606,
            "physical": 16655,
            "totalpower": 36600,
            "skill": 0.5
        },
        "154": {
            "id": 154,
            "character": "Muni",
            "cardname": "Witch Muni-Chan",
            "unit": "HapiAra",
            "type": "Cute",
            "rarity": 3,
            "heart": 9331,
            "technical": 8621,
            "physical": 9353,
            "totalpower": 27305,
            "skill": 0.25
        },
        "155": {
            "id": 155,
            "character": "Nagisa",
            "cardname": "1st Anniversary",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 4,
            "heart": 12194,
            "technical": 17876,
            "physical": 6960,
            "totalpower": 37030,
            "skill": 0.5
        },
        "156": {
            "id": 156,
            "character": "Nagisa",
            "cardname": "Azure Magical DJ",
            "unit": "Rondo",
            "type": "Elegant",
            "rarity": 3,
            "heart": 10318,
            "technical": 7489,
            "physical": 9771,
            "totalpower": 27578,
            "skill": 0.25
        },
        "157": {
            "id": 157,
            "character": "Nagisa",
            "cardname": "Birthday",
            "unit": "Rondo",
            "type": "Party",
            "rarity": 4,
            "heart": 11335,
            "technical": 11239,
            "physical": 12075,
            "totalpower": 34649,
            "skill": 0.5
        },
        "158": {
            "id": 158,
            "character": "Nagisa",
            "cardname": "Blue Rose Player",
            "unit": "Rondo",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11088,
            "technical": 12277,
            "physical": 10740,
            "totalpower": 34105,
            "skill": 0.3
        },
        "159": {
            "id": 159,
            "character": "Nagisa",
            "cardname": "God Speed Shooter",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 4,
            "heart": 16724,
            "technical": 6702,
            "physical": 11922,
            "totalpower": 35348,
            "skill": 0.4
        },
        "160": {
            "id": 160,
            "character": "Nagisa",
            "cardname": "Hazy Moon Player",
            "unit": "Rondo",
            "type": "Street",
            "rarity": 4,
            "heart": 11069,
            "technical": 10884,
            "physical": 12629,
            "totalpower": 34582,
            "skill": 0.4
        },
        "161": {
            "id": 161,
            "character": "Nagisa",
            "cardname": "Like a Fish to Water",
            "unit": "Rondo",
            "type": "Cool",
            "rarity": 4,
            "heart": 10520,
            "technical": 10964,
            "physical": 12514,
            "totalpower": 33998,
            "skill": 0.4
        },
        "162": {
            "id": 162,
            "character": "Nagisa",
            "cardname": "Sweetest Temptations",
            "unit": "Rondo",
            "type": "Party",
            "rarity": 3,
            "heart": 9015,
            "technical": 9067,
            "physical": 9790,
            "totalpower": 27872,
            "skill": 0.25
        },
        "163": {
            "id": 163,
            "character": "Nagisa",
            "cardname": "Twilight Notes",
            "unit": "Rondo",
            "type": "Cool",
            "rarity": 3,
            "heart": 10215,
            "technical": 9394,
            "physical": 8805,
            "totalpower": 28414,
            "skill": 0.25
        },
        "164": {
            "id": 164,
            "character": "Nagisa",
            "cardname": "Wild Solo",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 3,
            "heart": 8490,
            "technical": 9767,
            "physical": 8863,
            "totalpower": 27120,
            "skill": 0.2
        },
        "165": {
            "id": 165,
            "character": "Nagisa",
            "cardname": "Winning Guitar",
            "unit": "Rondo",
            "type": "Elegant",
            "rarity": 3,
            "heart": 9892,
            "technical": 10411,
            "physical": 6986,
            "totalpower": 27289,
            "skill": 0.25
        },
        "166": {
            "id": 166,
            "character": "Noa",
            "cardname": "1st Anniversary",
            "unit": "Photon",
            "type": "Cute",
            "rarity": 4,
            "heart": 15925,
            "technical": 12825,
            "physical": 6923,
            "totalpower": 35673,
            "skill": 0.5
        },
        "167": {
            "id": 167,
            "character": "Noa",
            "cardname": "Birthday",
            "unit": "Photon",
            "type": "Street",
            "rarity": 4,
            "heart": 11662,
            "technical": 11217,
            "physical": 12008,
            "totalpower": 34887,
            "skill": 0.5
        },
        "168": {
            "id": 168,
            "character": "Noa",
            "cardname": "Brilliant Hydrangea",
            "unit": "Photon",
            "type": "Elegant",
            "rarity": 4,
            "heart": 12425,
            "technical": 11650,
            "physical": 10925,
            "totalpower": 35000,
            "skill": 0.6
        },
        "169": {
            "id": 169,
            "character": "Noa",
            "cardname": "Cute Bringer",
            "unit": "Photon",
            "type": "Elegant",
            "rarity": 3,
            "heart": 8710,
            "technical": 9695,
            "physical": 8537,
            "totalpower": 26942,
            "skill": 0.2
        },
        "170": {
            "id": 170,
            "character": "Noa",
            "cardname": "Enchanted Lamp",
            "unit": "Photon",
            "type": "Cute",
            "rarity": 3,
            "heart": 12054,
            "technical": 11075,
            "physical": 8897,
            "totalpower": 32026,
            "skill": 0.25
        },
        "171": {
            "id": 171,
            "character": "Noa",
            "cardname": "Fantastic Lantern",
            "unit": "Photon",
            "type": "Cool",
            "rarity": 4,
            "heart": 12008,
            "technical": 11366,
            "physical": 10629,
            "totalpower": 34003,
            "skill": 0.4
        },
        "172": {
            "id": 172,
            "character": "Noa",
            "cardname": "Lemonade Flash",
            "unit": "Photon",
            "type": "Street",
            "rarity": 4,
            "heart": 11883,
            "technical": 6847,
            "physical": 16380,
            "totalpower": 35110,
            "skill": 0.4
        },
        "173": {
            "id": 173,
            "character": "Noa",
            "cardname": "Love Injection",
            "unit": "Photon",
            "type": "Street",
            "rarity": 3,
            "heart": 10971,
            "technical": 12724,
            "physical": 8281,
            "totalpower": 31976,
            "skill": 0.25
        },
        "174": {
            "id": 174,
            "character": "Noa",
            "cardname": "Melty Smile",
            "unit": "Photon",
            "type": "Party",
            "rarity": 3,
            "heart": 9126,
            "technical": 8735,
            "physical": 9545,
            "totalpower": 27406,
            "skill": 0.25
        },
        "175": {
            "id": 175,
            "character": "Noa",
            "cardname": "Sky Drifter",
            "unit": "Photon",
            "type": "Party",
            "rarity": 4,
            "heart": 10932,
            "technical": 12001,
            "physical": 11085,
            "totalpower": 34018,
            "skill": 0.3
        },
        "176": {
            "id": 176,
            "character": "Noa",
            "cardname": "Sweet Cookie",
            "unit": "Photon",
            "type": "Cute",
            "rarity": 4,
            "heart": 11791,
            "technical": 11314,
            "physical": 10634,
            "totalpower": 33739,
            "skill": 0.4
        },
        "177": {
            "id": 177,
            "character": "Rei",
            "cardname": "1st Anniversary",
            "unit": "HapiAra",
            "type": "Elegant",
            "rarity": 4,
            "heart": 16883,
            "technical": 12002,
            "physical": 7126,
            "totalpower": 36011,
            "skill": 0.5
        },
        "178": {
            "id": 178,
            "character": "Rei",
            "cardname": "Birthday Banquet",
            "unit": "HapiAra",
            "type": "Cool",
            "rarity": 4,
            "heart": 11120,
            "technical": 12881,
            "physical": 12633,
            "totalpower": 36634,
            "skill": 0.55
        },
        "179": {
            "id": 179,
            "character": "Rei",
            "cardname": "Birthday",
            "unit": "HapiAra",
            "type": "Cute",
            "rarity": 4,
            "heart": 13046,
            "technical": 11070,
            "physical": 10677,
            "totalpower": 34793,
            "skill": 0.5
        },
        "180": {
            "id": 180,
            "character": "Rei",
            "cardname": "Bubble Show Time",
            "unit": "HapiAra",
            "type": "Cool",
            "rarity": 4,
            "heart": 10859,
            "technical": 10696,
            "physical": 11710,
            "totalpower": 33265,
            "skill": 0.4
        },
        "181": {
            "id": 181,
            "character": "Rei",
            "cardname": "Drive Symphony",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 4,
            "heart": 11453,
            "technical": 12511,
            "physical": 11056,
            "totalpower": 35020,
            "skill": 0.3
        },
        "182": {
            "id": 182,
            "character": "Rei",
            "cardname": "Good Fortune Ahead 2021",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 3,
            "heart": 9213,
            "technical": 9275,
            "physical": 9186,
            "totalpower": 27674,
            "skill": 0.25
        },
        "183": {
            "id": 183,
            "character": "Rei",
            "cardname": "Kind-Hearted Healer",
            "unit": "HapiAra",
            "type": "Cute",
            "rarity": 3,
            "heart": 8949,
            "technical": 10053,
            "physical": 9359,
            "totalpower": 28361,
            "skill": 0.25
        },
        "184": {
            "id": 184,
            "character": "Rei",
            "cardname": "Pop Coffee Mug",
            "unit": "HapiAra",
            "type": "Street",
            "rarity": 3,
            "heart": 8779,
            "technical": 10375,
            "physical": 9831,
            "totalpower": 28985,
            "skill": 0.2
        },
        "185": {
            "id": 185,
            "character": "Rei",
            "cardname": "Secret Love On The Lips",
            "unit": "HapiAra",
            "type": "Elegant",
            "rarity": 3,
            "heart": 8859,
            "technical": 11005,
            "physical": 12599,
            "totalpower": 32463,
            "skill": 0.25
        },
        "186": {
            "id": 186,
            "character": "Rei",
            "cardname": "Splash Shower",
            "unit": "HapiAra",
            "type": "Street",
            "rarity": 4,
            "heart": 12498,
            "technical": 14972,
            "physical": 7140,
            "totalpower": 34610,
            "skill": "40+15%"
        },
        "187": {
            "id": 187,
            "character": "Rika",
            "cardname": "1st Anniversary",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 4,
            "heart": 16608,
            "technical": 7277,
            "physical": 12216,
            "totalpower": 36101,
            "skill": 0.5
        },
        "188": {
            "id": 188,
            "character": "Rika",
            "cardname": "Aqua Splash",
            "unit": "Mermaid",
            "type": "Cute",
            "rarity": 4,
            "heart": 11565,
            "technical": 11143,
            "physical": 11439,
            "totalpower": 34147,
            "skill": 0.3
        },
        "189": {
            "id": 189,
            "character": "Rika",
            "cardname": "Birthday",
            "unit": "Mermaid",
            "type": "Street",
            "rarity": 4,
            "heart": 11775,
            "technical": 11201,
            "physical": 11578,
            "totalpower": 34554,
            "skill": 0.5
        },
        "190": {
            "id": 190,
            "character": "Rika",
            "cardname": "Butterfly Parade",
            "unit": "Mermaid",
            "type": "Cute",
            "rarity": 3,
            "heart": 7689,
            "technical": 10510,
            "physical": 9514,
            "totalpower": 27713,
            "skill": 0.25
        },
        "191": {
            "id": 191,
            "character": "Rika",
            "cardname": "Hear My Longing",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 4,
            "heart": 11429,
            "technical": 10911,
            "physical": 11786,
            "totalpower": 34126,
            "skill": 0.4
        },
        "192": {
            "id": 192,
            "character": "Rika",
            "cardname": "Hype Stage",
            "unit": "Mermaid",
            "type": "Street",
            "rarity": 3,
            "heart": 10240,
            "technical": 8820,
            "physical": 9932,
            "totalpower": 28992,
            "skill": 0.2
        },
        "193": {
            "id": 193,
            "character": "Rika",
            "cardname": "Hype Up 777",
            "unit": "Mermaid",
            "type": "Cute",
            "rarity": 3,
            "heart": 9779,
            "technical": 8971,
            "physical": 9711,
            "totalpower": 28461,
            "skill": 0.25
        },
        "194": {
            "id": 194,
            "character": "Rika",
            "cardname": "Jump Into the World",
            "unit": "Mermaid",
            "type": "Street",
            "rarity": 3,
            "heart": 9414,
            "technical": 9219,
            "physical": 8982,
            "totalpower": 27615,
            "skill": 0.25
        },
        "195": {
            "id": 195,
            "character": "Rika",
            "cardname": "On This Fine Day",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 4,
            "heart": 12730,
            "technical": 6327,
            "physical": 15461,
            "totalpower": 34518,
            "skill": 0.4
        },
        "196": {
            "id": 196,
            "character": "Rika",
            "cardname": "Present From A Shining Star",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 4,
            "heart": 7128,
            "technical": 15992,
            "physical": 13163,
            "totalpower": 36283,
            "skill": 0.5
        },
        "197": {
            "id": 197,
            "character": "Rika",
            "cardname": "Sick Blast",
            "unit": "Mermaid",
            "type": "Party",
            "rarity": 4,
            "heart": 11123,
            "technical": 11220,
            "physical": 12287,
            "totalpower": 34630,
            "skill": 0.4
        },
        "198": {
            "id": 198,
            "character": "Rinku",
            "cardname": "1st Anniversary",
            "unit": "HapiAra",
            "type": "Cute",
            "rarity": 4,
            "heart": 17479,
            "technical": 6798,
            "physical": 11984,
            "totalpower": 36261,
            "skill": 0.5
        },
        "199": {
            "id": 199,
            "character": "Rinku",
            "cardname": "Because I Want Your Heart",
            "unit": "HapiAra",
            "type": "Elegant",
            "rarity": 4,
            "heart": 12243,
            "technical": 6981,
            "physical": 17843,
            "totalpower": 37067,
            "skill": 0.5
        },
        "200": {
            "id": 200,
            "character": "Rinku",
            "cardname": "Birthday",
            "unit": "HapiAra",
            "type": "Street",
            "rarity": 4,
            "heart": 11329,
            "technical": 11793,
            "physical": 11662,
            "totalpower": 34784,
            "skill": 0.5
        },
        "201": {
            "id": 201,
            "character": "Rinku",
            "cardname": "Fancy Surprise",
            "unit": "HapiAra",
            "type": "Elegant",
            "rarity": 4,
            "heart": 12143,
            "technical": 10636,
            "physical": 11344,
            "totalpower": 34123,
            "skill": 0.4
        },
        "202": {
            "id": 202,
            "character": "Rinku",
            "cardname": "Fortunate Portent 2021",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 3,
            "heart": 9082,
            "technical": 9219,
            "physical": 9348,
            "totalpower": 27649,
            "skill": 0.25
        },
        "203": {
            "id": 203,
            "character": "Rinku",
            "cardname": "Happy Hot Cocoa",
            "unit": "HapiAra",
            "type": "Cool",
            "rarity": 4,
            "heart": 14283,
            "technical": 14005,
            "physical": 7122,
            "totalpower": 35410,
            "skill": 0.6
        },
        "204": {
            "id": 204,
            "character": "Rinku",
            "cardname": "Happy Sky High",
            "unit": "HapiAra",
            "type": "Cute",
            "rarity": 3,
            "heart": 10140,
            "technical": 8917,
            "physical": 8495,
            "totalpower": 27552,
            "skill": 0.2
        },
        "205": {
            "id": 205,
            "character": "Rinku",
            "cardname": "Hero in Memory",
            "unit": "HapiAra",
            "type": "Cute",
            "rarity": 4,
            "heart": 11618,
            "technical": 11405,
            "physical": 11697,
            "totalpower": 34720,
            "skill": 0.4
        },
        "206": {
            "id": 206,
            "character": "Rinku",
            "cardname": "Reach The Sky",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 4,
            "heart": 12648,
            "technical": 14845,
            "physical": 7012,
            "totalpower": 34505,
            "skill": "40+15%"
        },
        "207": {
            "id": 207,
            "character": "Rinku",
            "cardname": "Sandy Beachball",
            "unit": "HapiAra",
            "type": "Street",
            "rarity": 3,
            "heart": 7384,
            "technical": 10253,
            "physical": 9745,
            "totalpower": 27382,
            "skill": 0.25
        },
        "208": {
            "id": 208,
            "character": "Rinku",
            "cardname": "Solidarity",
            "unit": "HapiAra",
            "type": "Party",
            "rarity": 4,
            "heart": 7048,
            "technical": 11735,
            "physical": 16309,
            "totalpower": 35092,
            "skill": 0.4
        },
        "209": {
            "id": 209,
            "character": "Rinku",
            "cardname": "Sunny Showtime",
            "unit": "HapiAra",
            "type": "Street",
            "rarity": 4,
            "heart": 11496,
            "technical": 11260,
            "physical": 11137,
            "totalpower": 33893,
            "skill": 0.3
        },
        "210": {
            "id": 210,
            "character": "Saki",
            "cardname": "1st Anniversary",
            "unit": "Photon",
            "type": "Street",
            "rarity": 4,
            "heart": 6895,
            "technical": 16144,
            "physical": 12835,
            "totalpower": 35874,
            "skill": 0.5
        },
        "211": {
            "id": 211,
            "character": "Saki",
            "cardname": "Angelic Intravenous",
            "unit": "Photon",
            "type": "Street",
            "rarity": 3,
            "heart": 8801,
            "technical": 12441,
            "physical": 10604,
            "totalpower": 31846,
            "skill": 0.25
        },
        "212": {
            "id": 212,
            "character": "Saki",
            "cardname": "Anthem Maiden",
            "unit": "Photon",
            "type": "Street",
            "rarity": 3,
            "heart": 9081,
            "technical": 9930,
            "physical": 8530,
            "totalpower": 27541,
            "skill": 0.2
        },
        "213": {
            "id": 213,
            "character": "Saki",
            "cardname": "Birthday",
            "unit": "Photon",
            "type": "Party",
            "rarity": 4,
            "heart": 11279,
            "technical": 11466,
            "physical": 12367,
            "totalpower": 35112,
            "skill": 0.5
        },
        "214": {
            "id": 214,
            "character": "Saki",
            "cardname": "Holic Candy",
            "unit": "Photon",
            "type": "Cute",
            "rarity": 3,
            "heart": 9401,
            "technical": 8628,
            "physical": 9822,
            "totalpower": 27851,
            "skill": 0.25
        },
        "215": {
            "id": 215,
            "character": "Saki",
            "cardname": "Midnight White Cat",
            "unit": "Photon",
            "type": "Street",
            "rarity": 4,
            "heart": 11120,
            "technical": 11885,
            "physical": 10470,
            "totalpower": 33475,
            "skill": 0.4
        },
        "216": {
            "id": 216,
            "character": "Saki",
            "cardname": "Moonlight Dance",
            "unit": "Photon",
            "type": "Cute",
            "rarity": 4,
            "heart": 17052,
            "technical": 6736,
            "physical": 12285,
            "totalpower": 36073,
            "skill": 0.5
        },
        "217": {
            "id": 217,
            "character": "Saki",
            "cardname": "Night Sky Glory",
            "unit": "Photon",
            "type": "Street",
            "rarity": 3,
            "heart": 7809,
            "technical": 9775,
            "physical": 10417,
            "totalpower": 28001,
            "skill": 0.25
        },
        "218": {
            "id": 218,
            "character": "Saki",
            "cardname": "Splash Fever",
            "unit": "Photon",
            "type": "Party",
            "rarity": 4,
            "heart": 11134,
            "technical": 11552,
            "physical": 11099,
            "totalpower": 33785,
            "skill": 0.4
        },
        "219": {
            "id": 219,
            "character": "Saki",
            "cardname": "Star Birth",
            "unit": "Photon",
            "type": "Cute",
            "rarity": 4,
            "heart": 10007,
            "technical": 13256,
            "physical": 11306,
            "totalpower": 34569,
            "skill": 0.3
        },
        "220": {
            "id": 220,
            "character": "Saori",
            "cardname": "1st Anniversary",
            "unit": "Mermaid",
            "type": "Party",
            "rarity": 4,
            "heart": 13094,
            "technical": 16581,
            "physical": 6789,
            "totalpower": 36464,
            "skill": 0.5
        },
        "221": {
            "id": 221,
            "character": "Saori",
            "cardname": "A Careless Delivery",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 3,
            "heart": 9090,
            "technical": 11629,
            "physical": 11183,
            "totalpower": 31902,
            "skill": 0.25
        },
        "222": {
            "id": 222,
            "character": "Saori",
            "cardname": "Birthday",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 4,
            "heart": 11881,
            "technical": 11036,
            "physical": 11445,
            "totalpower": 34362,
            "skill": 0.5
        },
        "223": {
            "id": 223,
            "character": "Saori",
            "cardname": "Birthday Fountain",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 4,
            "heart": 12919,
            "technical": 11511,
            "physical": 12302,
            "totalpower": 36732,
            "skill": 0.55
        },
        "224": {
            "id": 224,
            "character": "Saori",
            "cardname": "Blasted Crazy",
            "unit": "Mermaid",
            "type": "Party",
            "rarity": 3,
            "heart": 9673,
            "technical": 9430,
            "physical": 9408,
            "totalpower": 28511,
            "skill": 0.25
        },
        "225": {
            "id": 225,
            "character": "Saori",
            "cardname": "Bridging Gaps",
            "unit": "Mermaid",
            "type": "Street",
            "rarity": 4,
            "heart": 11876,
            "technical": 12169,
            "physical": 10980,
            "totalpower": 35025,
            "skill": 0.3
        },
        "226": {
            "id": 226,
            "character": "Saori",
            "cardname": "Critical Jackpot",
            "unit": "Mermaid",
            "type": "Cute",
            "rarity": 4,
            "heart": 10894,
            "technical": 11257,
            "physical": 11407,
            "totalpower": 33558,
            "skill": 0.4
        },
        "227": {
            "id": 227,
            "character": "Saori",
            "cardname": "Dancing Together",
            "unit": "Mermaid",
            "type": "Street",
            "rarity": 3,
            "heart": 9726,
            "technical": 9914,
            "physical": 8839,
            "totalpower": 28479,
            "skill": 0.25
        },
        "228": {
            "id": 228,
            "character": "Saori",
            "cardname": "In This Shining World",
            "unit": "Mermaid",
            "type": "Elegant",
            "rarity": 4,
            "heart": 6501,
            "technical": 12538,
            "physical": 15345,
            "totalpower": 34384,
            "skill": 0.4
        },
        "229": {
            "id": 229,
            "character": "Saori",
            "cardname": "Lost Child of Inari",
            "unit": "Mermaid",
            "type": "Cool",
            "rarity": 4,
            "heart": 15379,
            "technical": 12386,
            "physical": 6874,
            "totalpower": 34639,
            "skill": 0.4
        },
        "230": {
            "id": 230,
            "character": "Saori",
            "cardname": "Sick Scratch",
            "unit": "Mermaid",
            "type": "Party",
            "rarity": 3,
            "heart": 8413,
            "technical": 10515,
            "physical": 8811,
            "totalpower": 27739,
            "skill": 0.2
        },
        "231": {
            "id": 231,
            "character": "Shinobu",
            "cardname": "1st Anniversary",
            "unit": "Peaky",
            "type": "Street",
            "rarity": 4,
            "heart": 7484,
            "technical": 12726,
            "physical": 16591,
            "totalpower": 36801,
            "skill": 0.5
        },
        "232": {
            "id": 232,
            "character": "Shinobu",
            "cardname": "Birthday",
            "unit": "Peaky",
            "type": "Cool",
            "rarity": 4,
            "heart": 11884,
            "technical": 11734,
            "physical": 11028,
            "totalpower": 34646,
            "skill": 0.5
        },
        "233": {
            "id": 233,
            "character": "Shinobu",
            "cardname": "Birthday Thrones",
            "unit": "Peaky",
            "type": "Elegant",
            "rarity": 4,
            "heart": 12254,
            "technical": 11908,
            "physical": 12439,
            "totalpower": 36601,
            "skill": 0.55
        },
        "234": {
            "id": 234,
            "character": "Shinobu",
            "cardname": "Fascination Cage",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 4,
            "heart": 11581,
            "technical": 12034,
            "physical": 11906,
            "totalpower": 35521,
            "skill": 0.4
        },
        "235": {
            "id": 235,
            "character": "Shinobu",
            "cardname": "Golden Yellow Magical DJ",
            "unit": "Peaky",
            "type": "Elegant",
            "rarity": 4,
            "heart": 15271,
            "technical": 6669,
            "physical": 12796,
            "totalpower": 34736,
            "skill": 0.4
        },
        "236": {
            "id": 236,
            "character": "Shinobu",
            "cardname": "No Brainer Cut In",
            "unit": "Peaky",
            "type": "Elegant",
            "rarity": 3,
            "heart": 8764,
            "technical": 9879,
            "physical": 8648,
            "totalpower": 27291,
            "skill": 0.2
        },
        "237": {
            "id": 237,
            "character": "Shinobu",
            "cardname": "No Stops Express",
            "unit": "Peaky",
            "type": "Street",
            "rarity": 4,
            "heart": 11148,
            "technical": 12591,
            "physical": 10644,
            "totalpower": 34383,
            "skill": 0.3
        },
        "238": {
            "id": 238,
            "character": "Shinobu",
            "cardname": "Provoke Cute Devil",
            "unit": "Peaky",
            "type": "Street",
            "rarity": 3,
            "heart": 9057,
            "technical": 10668,
            "physical": 9049,
            "totalpower": 28774,
            "skill": 0.25
        },
        "239": {
            "id": 239,
            "character": "Shinobu",
            "cardname": "Sleet Consonance",
            "unit": "Peaky",
            "type": "Street",
            "rarity": 3,
            "heart": 11430,
            "technical": 9072,
            "physical": 8065,
            "totalpower": 28567,
            "skill": 0.25
        },
        "240": {
            "id": 240,
            "character": "Shinobu",
            "cardname": "The Flaming Kunoichi",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 4,
            "heart": 15876,
            "technical": 6817,
            "physical": 11643,
            "totalpower": 34336,
            "skill": 0.6
        },
        "241": {
            "id": 241,
            "character": "Shinobu",
            "cardname": "Tiger Gaze 2022",
            "unit": "Peaky",
            "type": "Elegant",
            "rarity": 3,
            "heart": 12319,
            "technical": 11578,
            "physical": 8475,
            "totalpower": 32372,
            "skill": 0.25
        },
        "242": {
            "id": 242,
            "character": "Shinobu",
            "cardname": "Wavering in Seven Colors",
            "unit": "Peaky",
            "type": "Cute",
            "rarity": 4,
            "heart": 15388,
            "technical": 12255,
            "physical": 6883,
            "totalpower": 34526,
            "skill": "40+15%"
        },
        "243": {
            "id": 243,
            "character": "Towa",
            "cardname": "1st Anniversary",
            "unit": "Photon",
            "type": "Cool",
            "rarity": 4,
            "heart": 7606,
            "technical": 12682,
            "physical": 16725,
            "totalpower": 37013,
            "skill": 0.5
        },
        "244": {
            "id": 244,
            "character": "Towa",
            "cardname": "Birthday",
            "unit": "Photon",
            "type": "Party",
            "rarity": 4,
            "heart": 11282,
            "technical": 11555,
            "physical": 11530,
            "totalpower": 34367,
            "skill": 0.5
        },
        "245": {
            "id": 245,
            "character": "Towa",
            "cardname": "Dazzling Bright",
            "unit": "Photon",
            "type": "Street",
            "rarity": 4,
            "heart": 12162,
            "technical": 10739,
            "physical": 11028,
            "totalpower": 33929,
            "skill": 0.3
        },
        "246": {
            "id": 246,
            "character": "Towa",
            "cardname": "Dazzling Sunny Days",
            "unit": "Photon",
            "type": "Cool",
            "rarity": 3,
            "heart": 9311,
            "technical": 8960,
            "physical": 8952,
            "totalpower": 27223,
            "skill": 0.25
        },
        "247": {
            "id": 247,
            "character": "Towa",
            "cardname": "Four-Leaf Clover",
            "unit": "Photon",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11660,
            "technical": 10545,
            "physical": 12795,
            "totalpower": 35000,
            "skill": 0.6
        },
        "248": {
            "id": 248,
            "character": "Towa",
            "cardname": "Funny Caramel",
            "unit": "Photon",
            "type": "Cute",
            "rarity": 4,
            "heart": 10962,
            "technical": 11965,
            "physical": 11788,
            "totalpower": 34715,
            "skill": 0.4
        },
        "249": {
            "id": 249,
            "character": "Towa",
            "cardname": "Powerful Bandage",
            "unit": "Photon",
            "type": "Street",
            "rarity": 4,
            "heart": 12029,
            "technical": 16789,
            "physical": 7116,
            "totalpower": 35934,
            "skill": 0.5
        },
        "250": {
            "id": 250,
            "character": "Towa",
            "cardname": "Pure Emotion",
            "unit": "Photon",
            "type": "Party",
            "rarity": 3,
            "heart": 10627,
            "technical": 8438,
            "physical": 8460,
            "totalpower": 27525,
            "skill": 0.2
        },
        "251": {
            "id": 251,
            "character": "Towa",
            "cardname": "Sparking Fish",
            "unit": "Photon",
            "type": "Street",
            "rarity": 3,
            "heart": 9562,
            "technical": 7786,
            "physical": 10759,
            "totalpower": 28107,
            "skill": 0.25
        },
        "252": {
            "id": 252,
            "character": "Tsubaki",
            "cardname": "1st Anniversary",
            "unit": "Rondo",
            "type": "Street",
            "rarity": 4,
            "heart": 16092,
            "technical": 12781,
            "physical": 6873,
            "totalpower": 35746,
            "skill": 0.5
        },
        "253": {
            "id": 253,
            "character": "Tsubaki",
            "cardname": "Birthday",
            "unit": "Rondo",
            "type": "Elegant",
            "rarity": 4,
            "heart": 11340,
            "technical": 11382,
            "physical": 11952,
            "totalpower": 34674,
            "skill": 0.5
        },
        "254": {
            "id": 254,
            "character": "Tsubaki",
            "cardname": "Birthday Museum",
            "unit": "Rondo",
            "type": "Cool",
            "rarity": 4,
            "heart": 12841,
            "technical": 11330,
            "physical": 12804,
            "totalpower": 36975,
            "skill": 0.55
        },
        "255": {
            "id": 255,
            "character": "Tsubaki",
            "cardname": "Canary In the Sky",
            "unit": "Rondo",
            "type": "Party",
            "rarity": 4,
            "heart": 11388,
            "technical": 11656,
            "physical": 10259,
            "totalpower": 33303,
            "skill": "40+15%"
        },
        "256": {
            "id": 256,
            "character": "Tsubaki",
            "cardname": "Electrifying Voice",
            "unit": "Rondo",
            "type": "Party",
            "rarity": 3,
            "heart": 8922,
            "technical": 10285,
            "physical": 9808,
            "totalpower": 29015,
            "skill": 0.2
        },
        "257": {
            "id": 257,
            "character": "Tsubaki",
            "cardname": "Hidden Feelings",
            "unit": "Rondo",
            "type": "Party",
            "rarity": 3,
            "heart": 9258,
            "technical": 9077,
            "physical": 9353,
            "totalpower": 27688,
            "skill": 0.25
        },
        "258": {
            "id": 258,
            "character": "Tsubaki",
            "cardname": "Moonlight Diva",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 4,
            "heart": 6650,
            "technical": 16474,
            "physical": 11292,
            "totalpower": 34416,
            "skill": 0.4
        },
        "259": {
            "id": 259,
            "character": "Tsubaki",
            "cardname": "Rainy Night Detective",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 3,
            "heart": 10493,
            "technical": 9881,
            "physical": 8021,
            "totalpower": 28395,
            "skill": 0.25
        },
        "260": {
            "id": 260,
            "character": "Tsubaki",
            "cardname": "Spring Evening Diva",
            "unit": "Rondo",
            "type": "Street",
            "rarity": 3,
            "heart": 9233,
            "technical": 8701,
            "physical": 9461,
            "totalpower": 27395,
            "skill": 0.25
        },
        "261": {
            "id": 261,
            "character": "Tsubaki",
            "cardname": "White Rose Diva",
            "unit": "Rondo",
            "type": "Cute",
            "rarity": 4,
            "heart": 11537,
            "technical": 11633,
            "physical": 10177,
            "totalpower": 33347,
            "skill": 0.3
        },
        "262": {
            "id": 262,
            "character": "Tsubaki",
            "cardname": "Wistful Blue Moon",
            "unit": "Rondo",
            "type": "Cool",
            "rarity": 4,
            "heart": 11437,
            "technical": 12473,
            "physical": 10808,
            "totalpower": 34718,
            "skill": 0.4
        },
        "263": {
            "id": 263,
            "character": "Yuka",
            "cardname": "1st Anniversary",
            "unit": "Peaky",
            "type": "Cool",
            "rarity": 4,
            "heart": 16573,
            "technical": 7454,
            "physical": 12123,
            "totalpower": 36150,
            "skill": 0.5
        },
        "264": {
            "id": 264,
            "character": "Yuka",
            "cardname": "Allure Spotlight",
            "unit": "Peaky",
            "type": "Cute",
            "rarity": 3,
            "heart": 8618,
            "technical": 9251,
            "physical": 10509,
            "totalpower": 28378,
            "skill": 0.2
        },
        "265": {
            "id": 265,
            "character": "Yuka",
            "cardname": "Awe Elegant Lady",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 3,
            "heart": 9655,
            "technical": 8513,
            "physical": 9134,
            "totalpower": 27302,
            "skill": 0.25
        },
        "266": {
            "id": 266,
            "character": "Yuka",
            "cardname": "Azure Sky -GRACE-",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 4,
            "heart": 11606,
            "technical": 6434,
            "physical": 15233,
            "totalpower": 33273,
            "skill": 0.4
        },
        "267": {
            "id": 267,
            "character": "Yuka",
            "cardname": "Birthday",
            "unit": "Peaky",
            "type": "Cool",
            "rarity": 4,
            "heart": 11490,
            "technical": 11630,
            "physical": 10519,
            "totalpower": 33639,
            "skill": 0.5
        },
        "268": {
            "id": 268,
            "character": "Yuka",
            "cardname": "Birthday Thrones",
            "unit": "Peaky",
            "type": "Cute",
            "rarity": 4,
            "heart": 12309,
            "technical": 12415,
            "physical": 12072,
            "totalpower": 36796,
            "skill": 0.55
        },
        "269": {
            "id": 269,
            "character": "Yuka",
            "cardname": "Bubbling Shot",
            "unit": "Peaky",
            "type": "Party",
            "rarity": 3,
            "heart": 9729,
            "technical": 10597,
            "physical": 7149,
            "totalpower": 27475,
            "skill": 0.25
        },
        "270": {
            "id": 270,
            "character": "Yuka",
            "cardname": "Drizzle Photogenic",
            "unit": "Peaky",
            "type": "Street",
            "rarity": 4,
            "heart": 16045,
            "technical": 6243,
            "physical": 11694,
            "totalpower": 33982,
            "skill": 0.4
        },
        "271": {
            "id": 271,
            "character": "Yuka",
            "cardname": "Soaring Lady Tengu",
            "unit": "Peaky",
            "type": "Cool",
            "rarity": 3,
            "heart": 9774,
            "technical": 9642,
            "physical": 7814,
            "totalpower": 27230,
            "skill": 0.25
        },
        "272": {
            "id": 272,
            "character": "Yuka",
            "cardname": "Train Line Bigbang",
            "unit": "Peaky",
            "type": "Elegant",
            "rarity": 4,
            "heart": 10610,
            "technical": 10796,
            "physical": 11828,
            "totalpower": 33234,
            "skill": 0.3
        },
        "273": {
            "id": 273,
            "character": "Yuka",
            "cardname": "Welcoming Spring 2022",
            "unit": "Peaky",
            "type": "Elegant",
            "rarity": 4,
            "heart": 16624,
            "technical": 11948,
            "physical": 7899,
            "totalpower": 36471,
            "skill": 0.5
        }
    }

/*
Template
        "": {
            "id": ,
            "character": "",
            "cardname": "",
            "unit": "",
            "type": "",
            "rarity": 4,
            "heart": ,
            "technical": ,
            "physical": ,
            "totalpower": ,
            "skill": 0.5
        }
*/

const cardArray = [];

Object.keys(cards).forEach(function(key) {
    var heart = cards[key].heart;
    var technical = cards[key].technical;
    var physical = cards[key].physical;
    var totalpower = parseInt(heart) + parseInt(technical) + parseInt(physical);
    cardArray.push({
        "id":cards[key].id,
        "character":cards[key].character,
        "cardname":cards[key].cardname,
        "unit":cards[key].unit,
        "type":cards[key].type,
        "rarity":cards[key].rarity,
        "heart":heart,
        "technical":technical,
        "physical":physical,
        "totalpower":totalpower,
        "skill":cards[key].skill
    })
});