var htl = {
    "name":"Here's The Light",
    "totalNotes":504,
    "level":12.5,
    "feverNotes":133,
    "sections":[
        {
            "notes":"20",
            "comboMult":"1",
            "skill":0,
            "gt":false
        },
        {
            "notes":"30",
            "comboMult":"1.01",
            "skill":0,
            "gt":false
        },
        {
            "notes":"16",
            "comboMult":"1.02",
            "skill":0,
            "gt":false
        },
        {
            "notes":"34",
            "comboMult":"1.02",
            "skill":1,
            "gt":false
        },
        {
            "notes":"6",
            "comboMult":"1.03",
            "skill":1,
            "gt":false
        },
        {
            "notes":"28",
            "comboMult":"1.03",
            "skill":0,
            "gt":false
        },
        {
            "notes":"16",
            "comboMult":"1.03",
            "skill":2,
            "gt":false
        },
        {
            "notes":"37",
            "comboMult":"1.04",
            "skill":2,
            "gt":false
        },
        {
            "notes":"13",
            "comboMult":"1.04",
            "skill":0,
            "gt":false
        },
        {
            "notes":"24",
            "comboMult":"1.05",
            "skill":0,
            "gt":false
        },
        {
            "notes":"26",
            "comboMult":"1.05",
            "skill":3,
            "gt":false
        },
        {
            "notes":"26",
            "comboMult":"1.06",
            "skill":3,
            "gt":false
        },
        {
            "notes":"22",
            "comboMult":"1.06",
            "skill":0,
            "gt":false
        },
        {
            "notes":"2",
            "comboMult":"1.06",
            "skill":4,
            "gt":false
        },
        {
            "notes":"50",
            "comboMult":"1.07",
            "skill":4,
            "gt":false
        },
        {
            "notes":"7",
            "comboMult":"1.07",
            "skill":4,
            "gt":false
        },
        {
            "notes":"7",
            "comboMult":"1.07",
            "skill":4,
            "gt":true
        },
        {
            "notes":"36",
            "comboMult":"1.07",
            "skill":0,
            "gt":true
        },
        {
            "notes":"30",
            "comboMult":"1.08",
            "skill":0,
            "gt":true
        },
        {
            "notes":"20",
            "comboMult":"1.08",
            "skill":5,
            "gt":true
        },
        {
            "notes":"23",
            "comboMult":"1.08",
            "skill":5,
            "gt":true
        },
        {
            "notes":"17",
            "comboMult":"1.08",
            "skill":0,
            "gt":true
        },
        {
            "notes":"10",
            "comboMult":"1.08",
            "skill":0,
            "gt":false
        },
        {
            "notes":"4",
            "comboMult":"1.09",
            "skill":0,
            "gt":false
        }
    ]
}

var cats = {
    "name":"Cat's Eye",
    "totalNotes":476,
    "level":11.5,
    "feverNotes":107,
    "sections": [
        {
            "notes":"20",
            "comboMult":"1",
            "skill":0,
            "gt":false
        },
        {
            "notes":"21",
            "comboMult":"1.01",
            "skill":0,
            "gt":false
        },
        {
            "notes":"9",
            "comboMult":"1.01",
            "skill":1,
            "gt":false
        },
        {
            "notes":"46",
            "comboMult":"1.02",
            "skill":1,
            "gt":false
        },
        {
            "notes":"4",
            "comboMult":"1.02",
            "skill":0,
            "gt":false
        },
        {
            "notes":"36",
            "comboMult":"1.03",
            "skill":0,
            "gt":false
        },
        {
            "notes":"14",
            "comboMult":"1.03",
            "skill":2,
            "gt":false
        },
        {
            "notes":"24",
            "comboMult":"1.04",
            "skill":2,
            "gt":false
        },
        {
            "notes":"26",
            "comboMult":"1.04",
            "skill":0,
            "gt":false
        },
        {
            "notes":"14",
            "comboMult":"1.05",
            "skill":0,
            "gt":false
        },
        {
            "notes":"36",
            "comboMult":"1.05",
            "skill":3,
            "gt":false
        },
        {
            "notes":"15",
            "comboMult":"1.06",
            "skill":3,
            "gt":false
        },
        {
            "notes":"35",
            "comboMult":"1.06",
            "skill":0,
            "gt":false
        },
        {
            "notes":"28",
            "comboMult":"1.07",
            "skill":0,
            "gt":false
        },
        {
            "notes":"41",
            "comboMult":"1.07",
            "skill":4,
            "gt":false
        },
        {
            "notes":"20",
            "comboMult":"1.07",
            "skill":4,
            "gt":true
        },
        {
            "notes":"11",
            "comboMult":"1.07",
            "skill":0,
            "gt":true
        },
        {
            "notes":"36",
            "comboMult":"1.08",
            "skill":0,
            "gt":true
        },
        {
            "notes":"39",
            "comboMult":"1.08",
            "skill":5,
            "gt":true
        },
        {
            "notes":"1",
            "comboMult":"1.08",
            "skill":0,
            "gt":true
        }
    ]
}

var directmedley = {
    "name":"Direct Drive x4 Medley",
    "totalNotes":582,
    "level":12,
    "feverNotes":123,
    "sections": [
        {
            "notes":"20",
            "comboMult":"1",
            "skill":0,
            "gt":false
        },
        {
            "notes":"30",
            "comboMult":"1.01",
            "skill":0,
            "gt":false
        },
        {
            "notes":"21",
            "comboMult":"1.02",
            "skill":0,
            "gt":false
        },
        {
            "notes":"29",
            "comboMult":"1.02",
            "skill":1,
            "gt":false
        },
        {
            "notes":"22",
            "comboMult":"1.03",
            "skill":1,
            "gt":false
        },
        {
            "notes":"28",
            "comboMult":"1.03",
            "skill":0,
            "gt":false
        },
        {
            "notes":"40",
            "comboMult":"1.04",
            "skill":0,
            "gt":false
        },
        {
            "notes":"10",
            "comboMult":"1.04",
            "skill":2,
            "gt":false
        },
        {
            "notes":"43",
            "comboMult":"1.05",
            "skill":2,
            "gt":false
        },
        {
            "notes":"7",
            "comboMult":"1.05",
            "skill":0,
            "gt":false
        },
        {
            "notes":"50",
            "comboMult":"1.06",
            "skill":0,
            "gt":false
        },
        {
            "notes":"6",
            "comboMult":"1.07",
            "skill":0,
            "gt":false
        },
        {
            "notes":"54",
            "comboMult":"1.07",
            "skill":3,
            "gt":false
        },
        {
            "notes":"40",
            "comboMult":"1.07",
            "skill":0,
            "gt":false
        },
        {
            "notes":"24",
            "comboMult":"1.08",
            "skill":0,
            "gt":false
        },
        {
            "notes":"34",
            "comboMult":"1.08",
            "skill":4,
            "gt":false
        },
        {
            "notes":"15",
            "comboMult":"1.08",
            "skill":4,
            "gt":true
        },
        {
            "notes":"27",
            "comboMult":"1.08",
            "skill":0,
            "gt":true
        },
        {
            "notes":"26",
            "comboMult":"1.09",
            "skill":0,
            "gt":true
        },
        {
            "notes":"43",
            "comboMult":"1.09",
            "skill":5,
            "gt":true
        },
        {
            "notes":"12",
            "comboMult":"1.09",
            "skill":0,
            "gt":true
        },
        {
            "notes":"1",
            "comboMult":"1.09",
            "skill":0,
            "gt":false
        }
    ]
}